GPU: [0]

VERBOSE: True

MODEL:
  MODE: 'Deraining'
  SESSION: 'DAIT'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 12
  NUM_EPOCHS: 300
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4  # 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  VAL_SAVE_EVERY: 50
  RESUME: False
  TRAIN_PS: 64
  VAL_PS: 64
  TRAIN_DIR: './Datasets/Synthetic_Rain_Datasets/train'       # path to training data(rain13k)
  VAL_DIR: './Datasets/Synthetic_Rain_Datasets/test/Rain100L' # path to validation data(rain100H、rain100L、Test100、Test1200、Test2800)
  SAVE_DIR: '/root/autodl-fs/checkpoints'           # path to save models and images
  # SAVE_IMAGES: False
